DROP TABLE PlaylistTrack CASCADE CONSTRAINTS;
DROP TABLE InvoiceLine CASCADE CONSTRAINTS;
DROP TABLE Track CASCADE CONSTRAINTS;
DROP TABLE Playlist CASCADE CONSTRAINTS;
DROP TABLE MediaType CASCADE CONSTRAINTS;
DROP TABLE Invoice CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Genre CASCADE CONSTRAINTS;
DROP TABLE Artist CASCADE CONSTRAINTS;
DROP TABLE Album CASCADE CONSTRAINTS;


-- DROP TABELAS NOVAS CRIADAS PELA PROCEDURE DINAMICA
DROP TABLE PlaylistTrack_alterado CASCADE CONSTRAINTS;
DROP TABLE InvoiceLine_alterado CASCADE CONSTRAINTS;
DROP TABLE Track_alterado CASCADE CONSTRAINTS;
DROP TABLE Playlist_alterado CASCADE CONSTRAINTS;
DROP TABLE MediaType_alterado CASCADE CONSTRAINTS;
DROP TABLE Invoice_alterado CASCADE CONSTRAINTS;
DROP TABLE Customer_alterado CASCADE CONSTRAINTS;
DROP TABLE Employee_alterado CASCADE CONSTRAINTS;
DROP TABLE Genre_alterado CASCADE CONSTRAINTS;
DROP TABLE Artist_alterado CASCADE CONSTRAINTS;
DROP TABLE Album_alterado CASCADE CONSTRAINTS;