-- 5. Implemente uma solução através da programação em banco de dados para validar os 
-- valores de uma coluna que represente uma situação (estado) garantindo que os seus 
-- valores e suas transições atendam a especificação de um diagrama de transição de 
-- estados (DTE). Quanto mais genérica e reutilizável for a solução melhor a pontuação 
-- nessa questão. Junto da solução deverá ser entregue um cenário de teste 
-- demonstrando o funcionamento da solução.