-- 3. Implementar procedimentos armazenados (stored procedures) que garantam a 
-- validação das regras semânticas criadas. Nesse caso, o mecanismo de permissões deve 
-- ser utilizado para criar um usuário que somente tenha acesso à manipulação dos dados 
-- envolvidos através do procedimento definido.
